<?php
/**
 * Created by PhpStorm.
 * User: pauk
 * Date: 6/15/19
 * Time: 6:10 PM
 */

namespace vova07\socio\models\backend;



use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;

use vova07\base\models\Ownableitem;

use vova07\documents\models\Document;
use vova07\socio\models\MaritalState;
use vova07\socio\models\MaritalStatus;
use vova07\socio\models\Relation;
use vova07\users\models\Person;

use yii\base\Behavior;
use yii\base\Event;
use yii\db\ActiveRecord;
use yii\db\Migration;
use yii\db\Schema;
use yii\helpers\ArrayHelper;


class RelationWithMarital extends  Relation
{

    public $marital_status_id;



    public function afterSave($insert, $changedAttributes)
    {
       // parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($this->marital_status_id){
            $maritalState = new MaritalState([
                '__person_id' =>$this->person_id,
                'ref_person_id' => $this->ref_person_id,
                'document_id' => $this->document_id,
                'status_id' => $this->marital_status_id
            ]);
            $maritalState->save();

        }
    }

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(),
            [
                [['marital_status_id'], 'integer']
            ]
        );
    }




}
