<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_PERMISSIONS_ATTR_CHILDREN' => '',
    'BACKEND_PERMISSIONS_ATTR_DATA' => '',
    'BACKEND_PERMISSIONS_ATTR_DESCRIPTION' => '',
    'BACKEND_PERMISSIONS_ATTR_NAME' => '',
    'BACKEND_PERMISSIONS_ATTR_RULE_NAME' => '',
    'BACKEND_PERMISSIONS_CHILDREN_PROMPT' => '',
    'BACKEND_PERMISSIONS_CREATE_SUBMIT' => '',
    'BACKEND_PERMISSIONS_CREATE_SUBTITLE' => '',
    'BACKEND_PERMISSIONS_CREATE_TITLE' => '',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_CREATE' => '',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_DELETE' => '',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_UPDATE' => '',
    'BACKEND_PERMISSIONS_INDEX_SUBTITLE' => '',
    'BACKEND_PERMISSIONS_INDEX_TITLE' => '',
    'BACKEND_PERMISSIONS_NOT_FOUND' => '',
    'BACKEND_PERMISSIONS_RULE_NAME_PROMPT' => '',
    'BACKEND_PERMISSIONS_UPDATE_SUBMIT' => '',
    'BACKEND_PERMISSIONS_UPDATE_SUBTITLE' => '',
    'BACKEND_PERMISSIONS_UPDATE_TITLE' => '',
    'BACKEND_ROLES_ATTR_DATA' => '',
    'BACKEND_ROLES_ATTR_DESCRIPTION' => '',
    'BACKEND_ROLES_ATTR_NAME' => '',
    'BACKEND_ROLES_ATTR_PERMISSIONS' => '',
    'BACKEND_ROLES_ATTR_ROLES' => '',
    'BACKEND_ROLES_ATTR_RULE_NAME' => '',
    'BACKEND_ROLES_CREATE_SUBMIT' => '',
    'BACKEND_ROLES_CREATE_SUBTITLE' => '',
    'BACKEND_ROLES_CREATE_TITLE' => '',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_CREATE' => '',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_DELETE' => '',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_UPDATE' => '',
    'BACKEND_ROLES_INDEX_SUBTITLE' => '',
    'BACKEND_ROLES_INDEX_TITLE' => '',
    'BACKEND_ROLES_NOT_FOUND' => '',
    'BACKEND_ROLES_PERMISSIONS_PROMPT' => '',
    'BACKEND_ROLES_ROLES_PROMPT' => '',
    'BACKEND_ROLES_RULE_NAME_PROMPT' => '',
    'BACKEND_ROLES_UPDATE_SUBMIT' => '',
    'BACKEND_ROLES_UPDATE_SUBTITLE' => '',
    'BACKEND_ROLES_UPDATE_TITLE' => '',
    'BACKEND_RULES_ATTR_NAME' => '',
    'BACKEND_RULES_ATTR_NAMESPACE' => '',
    'BACKEND_RULES_CREATE_SUBMIT' => '',
    'BACKEND_RULES_CREATE_SUBTITLE' => '',
    'BACKEND_RULES_CREATE_TITLE' => '',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_CREATE' => '',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_DELETE' => '',
    'BACKEND_RULES_INDEX_SUBTITLE' => '',
    'BACKEND_RULES_INDEX_TITLE' => '',
    'BACKEND_RULES_NOT_FOUND' => '',
    'ERROR_MSG_INVALID_CHILDREN' => '',
    'ERROR_MSG_INVALID_NAMESPACE' => '',
    'ERROR_MSG_INVALID_PERMISSIONS_CHILDREN' => '',
    'ERROR_MSG_INVALID_ROLES_CHILDREN' => '',
    'ERROR_MSG_INVALID_RULE_NAME' => '',
];
