<?php
/**
 * Created by PhpStorm.
 * User: pauk
 * Date: 8/2/19
 * Time: 1:32 PM
 */

namespace vova07\base\components;


use lajax\translatemanager\helpers\Language;
use yii\filters\AccessControl;

class BackendController extends \yii\web\Controller
{
    public $isPrintVersion = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['accessBackend']
                    ]
                ]
            ]
        ];
    }
    public function beforeAction($action)
    {
        if (\Yii::$app->request->get('print',false)){

                $this->isPrintVersion = true;
                $this->layout = '@vova07/themes/adminlte2/views/layouts/print.php';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}